- hosts: ose-master01.shiftlogic.io
  name: Ping OpenShift Master and Create a Project
  become: yes
  tasks:
    - name: ping the openshift master
      ping:
    - name: log into openshift
      command: oc login --token={{ token }} --server=https://{{ master }}
    - name: create a project
      command: /usr/bin/oc new-project newone3
      always_run: yes
    - name: list projects
      command: /usr/bin/oc projects
      always_run: yes

      
