- hosts: ose-master01.shiftlogic.io
  name: Ping OpenShift Master and Create a Project
  become: yes
  tasks:
    - name: ping the openshift master
      ping:
    - name: log into openshift
      command: oc login --token={{ token }} --server=https://openshift-master.shiftlogic.io
    - name: create a project
      command: /usr/bin/oc new-project newone
      always_run: yes
    - name: list projects
      command: /usr/bin/oc list-projects
      always_run: yes

      
